function RBH_Help(cmd)
	if cmd == "" or cmd == nil then
        RBH_LargessMessage("","sys")
        RBH_LargessMessage("--------------------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter v"..RBH_VERSION,"sys")
        RBH_LargessMessage("by Azinath","sys")
        RBH_LargessMessage("--------------------------------------","sys")
		RBH_LargessMessage("usage: /rbh <command> <args>","sys")
		RBH_LargessMessage("Type '/rbh help <command>' for info on a specific rbh command.","sys")
		RBH_LargessMessage("","sys")
		RBH_LargessMessage("Available rbh commands:","sys")		
		RBH_LargessMessage("   bounty","sys")
        RBH_LargessMessage("   claimown", "sys")
		RBH_LargessMessage("   classcolors", "sys")
		RBH_LargessMessage("   clear","sys")	
        RBH_LargessMessage("   scale","sys")
		RBH_LargessMessage("   sync","sys")    
        RBH_LargessMessage("   users","sys")     
	elseif cmd == "bounty" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Bounty","sys")
        RBH_LargessMessage("-----------------------------","sys")
		RBH_LargessMessage("useage: /rbh bounty [<amount> | bg <amount>]","sys")
		RBH_LargessMessage("Opens the add bounty dialog box populated with current target data.","sys")
		RBH_LargessMessage("If an amount is included \(in copper\) then the dialog box will not open and a bounty will be placed on the current target for the specified amount.","sys")
		RBH_LargessMessage("It may be useful to create a macro like: /rbh bounty 10123","sys")
		RBH_LargessMessage("This macro could be used to quickly add a bounty to your target for 1g 1s 23c","sys")
		RBH_LargessMessage("The 'bg <amount>' option only works in a battleground.","sys")
		RBH_LargessMessage("It adds a bounty for <amount> on every enemy player currently in the battleground.","sys")
		RBH_LargessMessage("Using the 'bg' option may require a refresh of the BG Stats list.","sys")
	elseif cmd == "claimown" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Claim Your Own Bounties","sys")
        RBH_LargessMessage("-----------------------------","sys")
		RBH_LargessMessage("useage: /rbh claimown [on | off]","sys")
        RBH_LargessMessage("Enable or disable your ability to claim bounties that you have issued.", "sys")
    elseif cmd == "classcolors" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Class Colors","sys")
        RBH_LargessMessage("-----------------------------","sys")
		RBH_LargessMessage("useage: /rbh classcolors [on | off]","sys")
        RBH_LargessMessage("Enable or disable class colors for names in the bounty list.", "sys")
    elseif cmd == "clear" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Clear","sys")
        RBH_LargessMessage("-----------------------------","sys")
		RBH_LargessMessage("useage: /rbh clear [all]","sys")
		RBH_LargessMessage("Clears your local bounty list.","sys")
		RBH_LargessMessage("Using the 'all' option also the clears the bounty lists for all online guild members.","sys")
		RBH_LargessMessage("The 'all' option requires officer note and guild info write permission.","sys")
	elseif cmd == "sync" then 
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Sync","sys")
        RBH_LargessMessage("-----------------------------","sys")
		RBH_LargessMessage("usage: /rbh sync","sys")
		RBH_LargessMessage("Forces a resynchronization of your bounty list with all online players registered in your channels.","sys")
		RBH_LargessMessage("This is done automatically on entering the game world and on UI reload.","sys")
    elseif cmd == "scale" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Set RBH UI Scale","sys")
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("usage: /rbh scale <scale>","sys")
        RBH_LargessMessage("Sets the scale of the main Realm Bounty Hunter UI frame.","sys")
    elseif cmd == "users" then
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("Realm Bounty Hunter","sys")
        RBH_LargessMessage("Lists Online Users","sys")
        RBH_LargessMessage("-----------------------------","sys")
        RBH_LargessMessage("usage: /rbh users","sys")
        RBH_LargessMessage("Reports back a list of RBH users online and their version number.","sys")
	end
end
